version: '3.3'

services:
  web:
    image: mlopswhereiswally/web:latest
    ports:
      - "8000:8000"
    depends_on:
      - api
  api:
    image: mlopswhereiswally/app:latest
    ports:
      - "5000:5000"

