stages:
  process_data:
    cmd: python -m src.features.process_data
    deps:
    - data/raw/train
    - data/raw/valid
    - data/raw/test
    
    outs:
    - data/processed/train
    - data/processed/valid
    - data/processed/test

  train:
    cmd: python -m src.models.train
    deps:
    - data/processed/train/images
    - src/models/train.py
    - params.yaml
    outs:
    - models/model.pt
    - reports/train_params.yaml:
        cache: false
    metrics:
    - reports/train_metrics.csv:
        cache: false

  evaluate:
    cmd: python -m src.models.evaluate
    deps:
    - data/processed/train
    - data/processed/test
    - models/yolov8_model.pkl
    metrics:
    - metrics/scores.json:
        cache: false


      