stages:
  prepare:
    cmd: python -m src.features.process_data
    deps:
    - data/raw/train/images
    - data/raw/valid/images
    - data/raw/test/images
    
    outs:
    - data/processed/train
    - data/processed/valid
    - data/processed/test

  train:
    cmd: python -m src.models.train
    deps:
    - data/processed/train/images
    - src/models/train.py
    - params.yaml
    outs:
    - models/model.pt
    - reports/train_params.yaml:
        cache: false
    metrics:
    - reports/train_metrics.csv:
        cache: false
      