
route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'ange.xu@estudiantat.upc.edu'
        auth_password: ""
        from: 'ange.xu@estudiantat.upc.edu'
        to: 'louis.van.langendonck@estudiantat.upc.edu'
