version: '3.1'

services:
  alertmanager:
    build:
        context: '.'
        dockerfile: dockerfile_alert
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
volumes:
    alertmanager-data:
